### ISSUE TITLE
Repeatable Crash

### ISSUE THREAD

**Issue by benjaml4** [AYapejian/node-red-contrib-home-assistant#44]
Hello I was wondering if you could help me, I'm facing an issue where node-red is crashing daily with this component. Docker reports the following from the node-red log:

27 Feb 22:01:21 - [red] Uncaught Exception:                                                                         
27 Feb 22:01:21 - TypeError: Cannot read property 'state' of null                                                   
    at ServerStateChangedNode.onHaEventsStateChanged (/data/node_modules/node-red-contrib-home-assistant/nodes/serve
r-events-state-changed/server-events-state-changed.js:38:42)                                                        
    at emitOne (events.js:121:20)                                                                                   
    at HaEvents.emit (events.js:211:7)                                                                              
    at HaEvents.onClientMessage (/data/node_modules/node-home-assistant/lib/ha-events.js:59:22)                     
    at EventSource.client.on (/data/node_modules/node-home-assistant/lib/ha-events.js:27:49)                        
    at emitOne (events.js:116:13)                                                                                   
    at EventSource.emit (events.js:211:7)                                                                           
    at _emit (/data/node_modules/eventsource/lib/eventsource.js:222:17)                                             
    at parseEventStreamLine (/data/node_modules/eventsource/lib/eventsource.js:237:9)                               
    at IncomingMessage.<anonymous> (/data/node_modules/eventsource/lib/eventsource.js:200:11) 

Can anyone help fix this for me as I'm unable to create a stable flow due to this stopping me from integrating Home Assistant and Node-Red.

Thanks,

Ben.

**Comment by walthowd** [comment]
It looks like Home Assistant is generating an event with a null state that is crashing Node-RED. 

You could start disabling some of your serve-state-changed (events: state) nodes to find the problematic node. 

Or, if you are an advanced user, you could put something like socat between Home Assistant and Node-RED to log all the events and use the timestamp from the crash to identify the entity.

**Comment by benjaml4** [comment]
Yeah that's what I assumed. Hopefully someone with better knowledge of this plugin can attempt to catch the null states that cause the plugin to crash and to handle them better. I'm also having issues with only a single node where something in the plugin code seems to stop my flow and I have to restart it making the whole system unstable. It's no fun when you press a light switch and nothing happens because the flow needs to be redeployed ;)

**Comment by oskargronqvist** [comment]
It seems like there is a missing try/catch that could fix the problem in onHaEventsStateChanged.
Try/catch is used in poll-state.js and trigger-state.js so I think adding one to server-events-state-changed.js wouldn't hurt even though it doesn't fix the source of the problem which probably is home assistant sending a null event to node red.

**Comment by Darksabre** [comment]
Eagerly awaiting this fix.  My Node-Red crashes every 30 minutes due to not handling Null states.

**Comment by dennisbrouwer91** [comment]
I have the same issue. Any update regarding this?

**Comment by flamingm0e** [comment]
Glad I found this report.  I thought it was my MQTT causing issues.  Now I see that HA is just sending null states to node-red.

**Comment by addd45** [comment]
Ok great, sorry for the misunderstanding.

**Comment by AYapejian** [comment]
Merged and released
