### ISSUE TITLE
install with npm: not a valid repo name

### ISSUE THREAD

**Issue by cbernet** [AYapejian/node-red-contrib-home-assistant#98]
**Describe the bug**

Install fails on raspberry pi 3 (raspbian stretch)

**To Reproduce**

```
cd ~/.node-red
npm install node-red-contrib-home-assistant
```
gives:

```
(node:8552) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm WARN package.json node-red-project@0.0.1 No repository field.
npm WARN package.json node-red-project@0.0.1 No README data
npm WARN package.json node-red-project@0.0.1 No license field.
npm ERR! git clone git@github.com:github:node-red/node-red Cloning into bare repository '/home/pi/.npm/_git-remotes/git-github-com-github-node-red-node-red-b505ab45'...
npm ERR! git clone git@github.com:github:node-red/node-red fatal: remote error: 
npm ERR! git clone git@github.com:github:node-red/node-red    is not a valid repository name
npm ERR! git clone git@github.com:github:node-red/node-red   Email support@github.com for help
npm ERR! notarget No compatible version found: node-red@'github:node-red/node-red#0.18.2'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.1.0","0.2.0","0.3.0","0.4.0","0.5.0","0.6.0","0.7.0","0.7.1","0.7.2","0.8.0","0.8.1","0.9.0","0.9.1","0.9.1-nocolors","0.10.0","0.10.1","0.10.2","0.10.3","0.10.4","0.10.6","0.10.8","0.10.8-2","0.10.8-3","0.10.9","0.10.10","0.11.0","0.11.1","0.11.2","0.12.0","0.12.1","0.12.2","0.12.3","0.12.4","0.12.5","0.13.0","0.13.1","0.13.2","0.13.3","0.13.4","0.14.0","0.14.1","0.14.2","0.14.3","0.14.4","0.14.5","0.14.6","0.15.0","0.15.1","0.15.2","0.15.3","0.16.0","0.16.1","0.16.2","0.17.0","0.17.2","0.17.3","0.17.4","0.17.5","0.18.0","0.18.1","0.18.2","0.18.3","0.18.4","0.18.5","0.18.6","0.18.7","0.19.0","0.19.1","0.19.2","0.19.3"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! System Linux 4.14.52-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "node-red-contrib-home-assistant"
npm ERR! cwd /home/pi/.node-red
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code ETARGET
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/.node-red/npm-debug.log
npm ERR! not ok code 0
```

**Expected behavior**

Install properly

**Environment (please complete the following information):**
 - Node Red Version: v0.18.7
 - NR Home Assistant Plugin Version: I don't have such a thing, but I could use nodered with home assistant using node-red-contrib-home-assistant when running in docker on another computer. Also, it seems to me the problem is related to the way npm decides on the git repository to use
 - Is Node Red running in Docker: no
 - npm Version: 1.4.21 
 - nodejs Version: v8.11.1

**Other (please complete the following information):**
- Have you searched previous issues for duplicates?: yes
- Did you attempt to reproduce the issue in the dev docker environment, if so what were results (See README.md): haven't tried. However,  I cound install this plugin in a node-red running in a docker container on my mac, by using the node-red palette manager.

**Additional context**

`git@github.com:github:node-red/node-red` is indeed not a valid repository name. 

I have tried many ways to install https://github.com/AYapejian/node-red-contrib-home-assistant with npm, to no avail, e.g.:

- provide arguments to npm to try and build the correct repo name, 
- cloning locally this repo to install the folder, 
- changing [this line](https://github.com/cbernet/node-red-contrib-home-assistant/commit/9b7f90e0b6aa12eecb038e506cd92e3d12c7bc9f) without knowing what I'm doing 

This last attempt brought me further: I can access the repository, but I get other errors later on: 

```
pi@raspberrypi:~/.node-red $ npm install cbernet/node-red-contrib-home-assistant
(node:10446) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm WARN package.json node-red-project@0.0.1 No repository field.
npm WARN package.json node-red-project@0.0.1 No README data
npm WARN package.json node-red-project@0.0.1 No license field.
npm WARN deprecated debug@3.2.4: `debug` versions 3.2.0-3.2.2 break Node 4. Users of node LTS and onward (modern Node versions): please upgrade to `debug@4` or above as soon as possible. Node 4 users: please pin to `debug@>=3.2.3 <4` as it will be the last version range that supports Node@4.
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/home/pi/.node-red/node_modules/node-red-contrib-home-assistant/node_modules/node-home-assistant/node_modules/chrono-node/src/parsers/ES'
npm ERR! error rolling back  node-home-assistant@0.2.1 { Error: ENOTEMPTY: directory not empty, rmdir '/home/pi/.node-red/node_modules/node-red-contrib-home-assistant/node_modules/node-home-assistant/node_modules/chrono-node/src/parsers/ES'
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/home/pi/.node-red/node_modules/node-red-contrib-home-assistant/node_modules/node-home-assistant/node_modules/chrono-node/src/parsers/ES' }
npm ERR! tar.unpack untar error /home/pi/.npm/yargs/8.0.2/package.tgz
npm ERR! tar.unpack untar error /home/pi/.npm/gl-matrix/2.8.1/package.tgz
npm ERR! tar.unpack untar error /home/pi/.npm/redeyed/1.0.1/package.tgz
npm ERR! tar.unpack untar error /home/pi/.npm/ansicolors/0.2.1/package.tgz
npm ERR! tar.unpack untar error /home/pi/.npm/xmlbuilder/9.0.7/package.tgz
npm ERR! tar.unpack untar error /home/pi/.npm/extsprintf/1.3.0/package.tgz
npm ERR! tar.unpack untar error /home/pi/.npm/json-schema/0.2.3/package.tgz
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/home/pi/.node-red/node_modules/node-red-contrib-home-assistant/node_modules/date-fns/end_of_year'
npm ERR! error rolling back  node-red-contrib-home-assistant@0.3.2 { Error: ENOTEMPTY: directory not empty, rmdir '/home/pi/.node-red/node_modules/node-red-contrib-home-assistant/node_modules/date-fns/end_of_year'
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/home/pi/.node-red/node_modules/node-red-contrib-home-assistant/node_modules/date-fns/end_of_year' }
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.14.52-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "cbernet/node-red-contrib-home-assistant"
npm ERR! cwd /home/pi/.node-red
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm ERR! tar.unpack untar error /home/pi/.npm/lodash/4.17.10/package.tgz
npm ERR! tar.unpack untar error /home/pi/.npm/breakword/1.0.3/package.tgz
npm ERR! tar.unpack untar error /home/pi/.npm/csv-stringify/3.1.1/package.tgz
npm ERR! tar.unpack untar error /home/pi/.npm/stream-transform/1.0.2/package.tgz
npm ERR! tar.unpack untar error /home/pi/.npm/ajv/5.5.2/package.tgz
npm ERR! tar.unpack untar error /home/pi/.npm/sshpk/1.14.2/package.tgz
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/home/pi/.node-red/node_modules/node-red-contrib-home-assistant/node_modules/node-home-assistant/node_modules/blessed-contrib/node_modules/picture-tube/node_modules/event-stream/node_modules/optimist/node_modules/wordwrap/test'
npm ERR! error rolling back  blessed-contrib@4.8.6 { Error: ENOTEMPTY: directory not empty, rmdir '/home/pi/.node-red/node_modules/node-red-contrib-home-assistant/node_modules/node-home-assistant/node_modules/blessed-contrib/node_modules/picture-tube/node_modules/event-stream/node_modules/optimist/node_modules/wordwrap/test'
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/home/pi/.node-red/node_modules/node-red-contrib-home-assistant/node_modules/node-home-assistant/node_modules/blessed-contrib/node_modules/picture-tube/node_modules/event-stream/node_modules/optimist/node_modules/wordwrap/test' }
npm ERR! tar.unpack untar error /home/pi/.npm/yargs/11.1.0/package.tgz
npm ERR! tar.unpack untar error /home/pi/.npm/csv-parse/2.5.0/package.tgz
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/home/pi/.node-red/node_modules/node-red-contrib-home-assistant/node_modules/node-home-assistant/node_modules/tty-table/node_modules/wcwidth/node_modules/defaults/node_modules/clone'
npm ERR! error rolling back  tty-table@2.6.8 { Error: ENOTEMPTY: directory not empty, rmdir '/home/pi/.node-red/node_modules/node-red-contrib-home-assistant/node_modules/node-home-assistant/node_modules/tty-table/node_modules/wcwidth/node_modules/defaults/node_modules/clone'
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/home/pi/.node-red/node_modules/node-red-contrib-home-assistant/node_modules/node-home-assistant/node_modules/tty-table/node_modules/wcwidth/node_modules/defaults/node_modules/clone' }
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/.node-red/npm-debug.log
npm ERR! not ok code 0
```  

Many thanks in advance for your help.

**Comment by cbernet** [comment]
I found out what is the problem: node-red and npm are completely outdated in raspbian stretch. 

Using the nodered installation instructions [here](https://nodered.org/docs/hardware/raspberrypi) gives a version of node-red where the manage palette menu item is available. With the manage palette, node-red-contrib-home-assistant can be installed. 

The version of npm that comes with this installation of nodered (npm 6.4.1) is much more recent, and I have tested that I can also install node-red-contrib-home-assistant with it.
